services:
  - type: web
    name: crypto-trading-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_SECRET
        generateValue: true
      - key: WEBHOOK_URL
        sync: false
